stages:
  - init
  - check
  - build
  - deploy

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - dist/

# 定义一个叫 init 的 Job 任务
init:
  stage: init
  script:
    - cnpm install

# master_check Job: 检查 master 分支上关键内容
master_check:
  stage: check
  script:
    - echo "Start Check Eros Config ..."
    - bash check.sh release
  only:
    - master

# dev_check Job: 检查 dev 分支上关键内容
dev_check:
  stage: check
  script:
    - echo "Start Check Eros Config ..."
    - bash check.sh debug
  only:
    - dev

# js_build Job: 构建项目
js_build:
  stage: build
  script:
    - eros build

# master_deploy Job: 部署到 master 分支
master_deploy:
  stage: deploy
  script:
    - bash deploy.sh release
  only:
    - master

# dev_deploy Job: 部署到 dev 分支
dev_deploy:
  stage: deploy
  script:
    - bash deploy.sh debug
  only:
    - dev
